/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClubManagerRole;

import Business.Club.*;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jiaaoyu
 */
public class ClubManagerUpdateJPanel extends javax.swing.JPanel {

    private JPanel container;
    private ClubDirectory clubDirectory;
    private EcoSystem system;
    private Club club;
    private UserAccount userAccount;

    /**
     * Creates new form ClubManagerUpdateJPanel
     */
    public ClubManagerUpdateJPanel(JPanel container, EcoSystem system, Club club, UserAccount userAccount) {
        initComponents();
        this.system = system;
        this.container = container;
        this.clubDirectory = system.getClubDirectory();
        this.club = club;
        this.userAccount = userAccount;

        setDefaultInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clubManagerNamejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clubManagerPasswordjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clubManagerAccountNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clubNamejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clubAddressjTextField = new javax.swing.JTextField();

        clubManagerNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clubManagerNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubManagerNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Club Manager Account :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Club Basic Information :");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Club Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Club Manager password :");

        clubManagerPasswordjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clubManagerPasswordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubManagerPasswordjTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Club Manager Account Name :");

        clubManagerAccountNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clubManagerAccountNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubManagerAccountNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Club Manager Name :");

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        createBtn.setText("Update");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Club Address :");

        clubNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clubNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Club Manager Information :");

        clubAddressjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clubAddressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubAddressjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubManagerPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubManagerAccountNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubManagerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(179, 179, 179)
                            .addComponent(clubNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(createBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clubNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clubAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clubManagerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clubManagerAccountNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(clubManagerPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clubManagerNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubManagerNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubManagerNamejTextFieldActionPerformed

    private void clubManagerPasswordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubManagerPasswordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubManagerPasswordjTextFieldActionPerformed

    private void clubManagerAccountNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubManagerAccountNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubManagerAccountNamejTextFieldActionPerformed

    private void setDefaultInfo() {
        clubNamejTextField.setText(club.getClubName());
        clubAddressjTextField.setText(club.getAddress());
        clubManagerNamejTextField.setText(userAccount.getPersonnel().getName());
        clubManagerAccountNamejTextField.setText(userAccount.getUsername());
        clubManagerPasswordjTextField.setText(userAccount.getPassword());
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClubManagerWorkAreaJPanel panel = (ClubManagerWorkAreaJPanel) component;

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String clubName = clubNamejTextField.getText();
        String clubAddress = clubAddressjTextField.getText();
        String clubManagerName = clubManagerNamejTextField.getText();
        String clubManagerAccountName = clubManagerAccountNamejTextField.getText();
        String clubManagerPassword = clubManagerPasswordjTextField.getText();

        if (clubName.equals("") || clubAddress.equals("") || clubManagerName.equals("") || clubManagerAccountName.equals("") || clubManagerPassword.equals("")) {
            setDefaultInfo();
            JOptionPane.showMessageDialog(null, "Please fill in all blanks!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (Club c : clubDirectory.getClubList()) {
            if (club.getClubName().equals(clubName)) {
                continue;
            }
            if (c.getClubName().equals(clubName)) {
                setDefaultInfo();
                JOptionPane.showMessageDialog(null, "Duplicated club name! Please pick another one!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if (!userAccount.getUsername().equals(clubManagerAccountName)) {
            if (!system.isFeasible(clubManagerAccountName)) {
                setDefaultInfo();
                JOptionPane.showMessageDialog(null, "Duplicated manager account name! Please pick another one!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        club.setClubName(clubName);
        club.setAddress(clubAddress);
        userAccount.getPersonnel().setName(clubManagerName);
        userAccount.setUsername(clubManagerAccountName);
        userAccount.setPassword(clubManagerPassword);
        JOptionPane.showMessageDialog(null, "Successfully updated!", "Successful", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_createBtnActionPerformed

    private void clubAddressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubAddressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubAddressjTextFieldActionPerformed

    private void clubNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubNamejTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField clubAddressjTextField;
    private javax.swing.JTextField clubManagerAccountNamejTextField;
    private javax.swing.JTextField clubManagerNamejTextField;
    private javax.swing.JTextField clubManagerPasswordjTextField;
    private javax.swing.JTextField clubNamejTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
