/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClubManagerRole;

import Business.Club.Club;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import UserInterface.ViewStatisticJPanel;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author lixuy
 */
public class ClubManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    private EcoSystem system;
    private Club club;
    private UserAccount userAccount;
    private Icon wallpaper;

    /**
     * Creates new form ClubManagerWorkAreaJPanel
     */
    public ClubManagerWorkAreaJPanel(JPanel container, Club club, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.container = container;
        this.club = club;
        this.system = system;
        this.userAccount = userAccount;
        this.setBackground(new ImageIcon("bg/bg6.jpg"));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (null != wallpaper) {
            processBackground(g);
        }
    }

    private void setBackground(Icon wallpaper) {
        this.wallpaper = wallpaper;
        this.repaint();
    }

    private void processBackground(Graphics g) {
        ImageIcon icon = (ImageIcon) wallpaper;
        Image image = icon.getImage();
        int cw = getWidth();
        int ch = getHeight();
        int iw = image.getWidth(this);
        int ih = image.getHeight(this);
        int x = 0;
        int y = 0;
        while (y <= ch) {
            g.drawImage(image, x, y, this);
            x += iw;
            if (x >= cw) {
                x = 0;
                y += ih;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePersonnelBtn = new javax.swing.JButton();
        squadBtn = new javax.swing.JButton();
        messageCenterBtn = new javax.swing.JButton();
        viewStatisticBtn = new javax.swing.JButton();
        manageAccountBtn = new javax.swing.JButton();
        transferPlayerBtn = new javax.swing.JButton();

        managePersonnelBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        managePersonnelBtn.setText("Manage Personnel");
        managePersonnelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonnelBtnActionPerformed(evt);
            }
        });

        squadBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        squadBtn.setText("Match Squad List");
        squadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squadBtnActionPerformed(evt);
            }
        });

        messageCenterBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        messageCenterBtn.setText("Message Center");
        messageCenterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageCenterBtnActionPerformed(evt);
            }
        });

        viewStatisticBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewStatisticBtn.setText("View Statistic");
        viewStatisticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatisticBtnActionPerformed(evt);
            }
        });

        manageAccountBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        manageAccountBtn.setText("Manage Account");
        manageAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountBtnActionPerformed(evt);
            }
        });

        transferPlayerBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        transferPlayerBtn.setText("Transfer Player");
        transferPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferPlayerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewStatisticBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(messageCenterBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(squadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(686, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(transferPlayerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePersonnelBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageAccountBtn)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managePersonnelBtn)
                    .addComponent(manageAccountBtn))
                .addGap(32, 32, 32)
                .addComponent(transferPlayerBtn)
                .addGap(32, 32, 32)
                .addComponent(squadBtn)
                .addGap(37, 37, 37)
                .addComponent(messageCenterBtn)
                .addGap(35, 35, 35)
                .addComponent(viewStatisticBtn)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void squadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squadBtnActionPerformed
        // TODO add your handling code here:
        ManageSquadListJPanel panel = new ManageSquadListJPanel(container, club, system.getLeagueDirectory());
        container.add("ManageSquadListJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_squadBtnActionPerformed

    private void messageCenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageCenterBtnActionPerformed
        // TODO add your handling code here:
        MessageCenterManagerJPanel panel = new MessageCenterManagerJPanel(container, userAccount, club, system);
        container.add("MessageCenterManagerJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_messageCenterBtnActionPerformed

    private void viewStatisticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatisticBtnActionPerformed
        // TODO add your handling code here:
        ViewStatisticJPanel panel = new ViewStatisticJPanel(container,system.getLeagueDirectory());
        JScrollPane jscrollPane1 =new JScrollPane(panel);
        
        container.add("ViewStatisticJPanel", jscrollPane1);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_viewStatisticBtnActionPerformed

    private void managePersonnelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonnelBtnActionPerformed
        // TODO add your handling code here:

        ManagePersonnelJPanel panel = new ManagePersonnelJPanel(container, system, club);
        container.add("ManagePersonnelJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_managePersonnelBtnActionPerformed

    private void manageAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountBtnActionPerformed
        // TODO add your handling code here:
        ClubManagerUpdateJPanel panel = new ClubManagerUpdateJPanel(container, system, club, userAccount);
        container.add("CreateClubJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageAccountBtnActionPerformed

    private void transferPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferPlayerBtnActionPerformed
        // TODO add your handling code here:
        TransferPlayerJPanel panel = new TransferPlayerJPanel(container, club, system);
        container.add("TransferPlayerJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_transferPlayerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageAccountBtn;
    private javax.swing.JButton managePersonnelBtn;
    private javax.swing.JButton messageCenterBtn;
    private javax.swing.JButton squadBtn;
    private javax.swing.JButton transferPlayerBtn;
    private javax.swing.JButton viewStatisticBtn;
    // End of variables declaration//GEN-END:variables
}
