/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Club.Club;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.League.League;
import Business.Match.Match;
import Business.Organization.Organization;
import Business.Personnel.Personnel;
import Business.Role.SoccerAssociationRole;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.*;
import org.jvnet.substance.skin.*;

/**
 *
 * @author lixuy
 */
public class MainJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
//        system = system.getInstance();

//        set soc and keyboardman id
        
//        for (Organization organization : system.getOrganizationDirectory().getOrganizationList()) {
//            if (organization.getName().equals("Soccer Association")) {
//                for (Personnel p : organization.getPersonnelDirectory().getPersonnelList()) {
//                    if (p.getName().equals("keyboardman")) {
//                        p.setId(-2);
//                    }
//                    if (p.getName().equals("soccer association")) {
//                        p.setId(-1);
//                    }
//                }
//            }
//        }

        League.count = system.getIdg().getlID();
        Club.count = system.getIdg().getcID();
        Organization.count = system.getIdg().getoID();
        Match.count = system.getIdg().getmID();
        Personnel.count = system.getIdg().getpID();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int flag = JOptionPane.showConfirmDialog(null, "Sure to close?", "Care!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (JOptionPane.YES_OPTION == flag) {
                    system.getIdg().setlID(League.count);
                    system.getIdg().setcID(Club.count);
                    system.getIdg().setoID(Organization.count);
                    system.getIdg().setmID(Match.count);
                    system.getIdg().setpID(Personnel.count);
                    dB4OUtil.storeSystem(system);
                    System.exit(0);
                } else {
                    return;
                }
            }
        });
        CardLayout layout = (CardLayout) fatherContainer.getLayout();
        fatherContainer.add("LoginJPanel", new LoginJPanel(system, dB4OUtil, fatherContainer));
        layout.next(fatherContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fatherContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soccer League Management System");
        setPreferredSize(new java.awt.Dimension(880, 520));

        fatherContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(fatherContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new SubstanceEmeraldDuskLookAndFeel());
                } catch (Exception e) {
                    System.err.println("failed to load LookAndFeel");
                }
                MainJFrame mj = new MainJFrame();
                mj.setVisible(true);
                mj.setResizable(false);
                mj.setSize(1024, 768);
                mj.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fatherContainer;
    // End of variables declaration//GEN-END:variables
}
