/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SoccerAssociationRole;

import Business.Match.Match;
import Business.Match.MatchDay;
import Business.Personnel.Personnel;
import Business.Personnel.PersonnelDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lixuy
 */
public class AssignRefereeJPanel extends javax.swing.JPanel {

    private JPanel container;
    private PersonnelDirectory personnelDirectory;
    private Match match;
    private MatchDay matchDay;
    
    /**
     * Creates new form AssignRefereeJPanel
     */
    AssignRefereeJPanel(JPanel container, PersonnelDirectory personnelDirectory, Match match, MatchDay matchDay) {
        initComponents();
        this.container = container;
        this.personnelDirectory = personnelDirectory;
        this.match = match;
        this.matchDay = matchDay;
        initComboBox();
        
    }
    
     private void initComboBox() {
         
         for(Personnel personnel: personnelDirectory.getPersonnelList())
             {
                 int flag = 0;
                  for(Match match: matchDay.getMatchList())
                  {
                  if(personnel == match.getReferee())
                    {
                      flag = 1;
                      break;
                    }
                  }
                  
                  if(flag == 0)
                  {
                   jComboBox.addItem(personnel);  
                  }
             }
                  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matchInfojLabel = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        matchInfojLabel1 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();

        matchInfojLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        matchInfojLabel.setText("Match Information:");

        assignBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        matchInfojLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        matchInfojLabel1.setText("Available Referee:");

        jComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matchInfojLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(assignBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(matchInfojLabel1)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchInfojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matchInfojLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assignBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMatchJPanel panel = (ManageMatchJPanel) component;
        panel.initComboBox();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        match.setReferee( (Personnel) jComboBox.getSelectedItem());
        match.setRefereeAssigned(true);
        
        JOptionPane.showMessageDialog(null, "Referee is successfully assigned to Match");
        
    }//GEN-LAST:event_assignBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel matchInfojLabel;
    private javax.swing.JLabel matchInfojLabel1;
    // End of variables declaration//GEN-END:variables

}
